# Generated by Django 4.1 on 2022-09-29 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appinicio', '0006_alter_post_content_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='password',
        ),
    ]
